In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv(r"C:\Users\SaintLaurentDon\Desktop\ML1\Machine Learning A-Z New\Part 7 - Natural Language Processing\Section 36 - Natural Language Processing\small_reviews.csv")

In [3]:
dataset.head()

Id                                             Review  Label
0   0                               good and interesting      5
1   1  This class is very helpful to me. Currently, I...      5
2   2  like!Prof and TAs are helpful and the discussi...      5
3   3  Easy to follow and includes a lot basic and im...      5
4   4  Really nice teacher!I could got the point eazl...      4

In [4]:
dataset['Label'].value_counts()

5    7139
4    1777
3     495
1     328
2     260
Name: Label, dtype: int64

In [5]:
dataset.drop('Id',axis=1,inplace=True)

In [6]:
# Cleaning the texts
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
corpus = []
for i in range(0, 9999):
    review = re.sub('[^a-zA-Z]', ' ', dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\SaintLaurentDon\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [7]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 50000)
X = cv.fit_transform(corpus).toarray()
y = dataset.iloc[:, -1].values

In [8]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.30, random_state = 0)


In [9]:
# Fitting Naive Bayes to the Training set
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()
nb.fit(X_train, y_train)


MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [10]:
# Predicting the Test set results
nb_pred = nb.predict(X_test)

In [11]:
# Making the Confusion Matrix
from sklearn.metrics import classification_report, confusion_matrix
cm = confusion_matrix(y_test, nb_pred)
print(cm)
print(classification_report(y_test,nb_pred))

[[  11    2    2   33   44]
 [   3    2    2   24   42]
 [   0    2    7   65   71]
 [   3    1    7  135  392]
 [   4    1    9   82 2056]]
              precision    recall  f1-score   support

           1       0.52      0.12      0.19        92
           2       0.25      0.03      0.05        73
           3       0.26      0.05      0.08       145
           4       0.40      0.25      0.31       538
           5       0.79      0.96      0.86      2152

    accuracy                           0.74      3000
   macro avg       0.44      0.28      0.30      3000
weighted avg       0.67      0.74      0.69      3000



In [13]:
x='This course is very good and very lovely'
print(nb.predict(cv.transform([x]))[0])

5


In [27]:
x='This course is very annoying and very irrelevant. the teacher has no idea what he teaches. no required information is given'
print(nb.predict(cv.transform([x]))[0])

2


In [ ]:
'''
# Fitting SVM to the Training set
from sklearn.svm import SVC
svm = SVC(kernel = 'linear', random_state = 0)
svm.fit(X_train, y_train)

# Predicting the Test set results
svm_pred = svm.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, svm_pred)
print(cm)
print(classification_report(y_test,svm_pred))
'''

In [ ]:
'''
x='This course is very helpful'
print(svm.predict(cv.transform([x]))[0])
'''

In [15]:
#Fitting Random Forest to the training set
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
rf.fit(X_train, y_train)

# Predicting the Test set results
rf_pred = rf.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, rf_pred)
print(cm)
print(classification_report(y_test,rf_pred))



[[  14    3    3   11   61]
 [   2    1    1   10   59]
 [   9    1    6   30   99]
 [   7    3   17   93  418]
 [  13    0    5   95 2039]]
              precision    recall  f1-score   support

           1       0.31      0.15      0.20        92
           2       0.12      0.01      0.02        73
           3       0.19      0.04      0.07       145
           4       0.39      0.17      0.24       538
           5       0.76      0.95      0.84      2152

    accuracy                           0.72      3000
   macro avg       0.35      0.27      0.28      3000
weighted avg       0.64      0.72      0.66      3000



In [16]:
x="This course is the worst i have taken on coursera. They just want to mention everything in very short time. Quiz is much harder than material on video."
print(rf.predict(cv.transform([x]))[0])

3


In [17]:
x="This course is very good and also contains lots of necessary details"
print(rf.predict(cv.transform([x]))[0])

5


In [28]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(criterion = 'entropy', random_state = 0,class_weight='balanced')
dt.fit(X_train, y_train)

# Predicting the Test set results
dt_pred = dt.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, dt_pred)
print(cm)
print(classification_report(y_test,rf_pred))

[[  31   14   15    7   25]
 [  15   12   18   10   18]
 [  19   14   17   41   54]
 [  24   22   40  151  301]
 [  76   44   64  341 1627]]
              precision    recall  f1-score   support

           1       0.31      0.15      0.20        92
           2       0.12      0.01      0.02        73
           3       0.19      0.04      0.07       145
           4       0.39      0.17      0.24       538
           5       0.76      0.95      0.84      2152

    accuracy                           0.72      3000
   macro avg       0.35      0.27      0.28      3000
weighted avg       0.64      0.72      0.66      3000



In [19]:
x="This course is the worst i have taken on coursera. They just want to mention everything in very short time. Quiz is much harder than material on video."
print(dt.predict(cv.transform([x]))[0])

1


In [20]:
x="This course is average also a normal intro"
print(dt.predict(cv.transform([x]))[0])

1


In [21]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver = 'lbfgs', random_state = 0)
lr.fit(X_train, y_train)

# Predicting the Test set results
lr_pred = lr.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, lr_pred)
print(cm)
print(classification_report(y_test,lr_pred))

C:\Users\SaintLaurentDon\Anaconda3\envs\gputest\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


[[  25   15    9   13   30]
 [   7    6   13   15   32]
 [   7    6   28   40   64]
 [   6   14   26  118  374]
 [   2    4   10  122 2014]]
              precision    recall  f1-score   support

           1       0.53      0.27      0.36        92
           2       0.13      0.08      0.10        73
           3       0.33      0.19      0.24       145
           4       0.38      0.22      0.28       538
           5       0.80      0.94      0.86      2152

    accuracy                           0.73      3000
   macro avg       0.44      0.34      0.37      3000
weighted avg       0.68      0.73      0.69      3000



In [22]:
x="This course is the worst i have taken on coursera. They just want to mention everything in very short time. Quiz is much harder than material on video."
print(lr.predict(cv.transform([x]))[0])

1


In [23]:
x="This course is very informative and good the teacher is very intelligent"
print(dt.predict(cv.transform([x]))[0])

5
